import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/common/Header/Header";
import { CartProvider } from "@/contexts/cartContext";
import Footer from "@/components/common/Footer/Footer";
import {Toaster} from "react-hot-toast"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProvider>
        <CartProvider>

<div className="mx-auto max-w-[1440px]">

         <Header/>
        {children}
       <Footer />
</div>
        </CartProvider>
        </ClerkProvider>
        <Toaster />
      </body>
    </html>
  );
}
